# Generated by Django 3.2.3 on 2021-05-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_twitter_id', models.CharField(max_length=32)),
                ('account_number', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0)),
            ],
        ),
    ]
