# Generated by Django 3.2.3 on 2021-05-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payments', models.IntegerField(default=0)),
                ('total_tnbc_paid', models.IntegerField(default=0)),
                ('average_tnbc_paid', models.IntegerField(default=0)),
                ('amount_paid_in_usd', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_twitter_id', models.CharField(max_length=32)),
                ('account_number', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payments', models.IntegerField(default=0)),
                ('total_tnbc_paid', models.IntegerField(default=0)),
                ('average_tnbc_paid', models.IntegerField(default=0)),
                ('amount_paid_in_usd', models.IntegerField(default=0)),
            ],
        ),
    ]
