# Generated by Django 3.2.3 on 2021-05-16 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payments', models.IntegerField(default=0)),
                ('total_tnbc_paid', models.IntegerField(default=0)),
                ('average_tnbc_paid', models.IntegerField(default=0)),
                ('amount_paid_in_usd', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='faucetmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 16, 2, 38, 40, 237796, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faucetmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
